version: "3.8"
services:
  server:
    build: ./packages/server
    container_name: server
    volumes:
      - '/usr/src/app/node_modules'
      - ./packages/server/:/usr/src/app/packages/server
    ports:
      - 3011:3011
    command:
      npm --prefix packages/server start
  frontend:
    build: ./packages/frontend
    restart: always
    container_name: frontend
    volumes:
      - "/usr/src/app/node_modules"
      - ./packages/frontend/:/usr/src/app/packages/frontend
    ports:
      - 4200:4200
    links:
      - server
    command:
      npm --prefix packages/frontend start

# version: "3.8"
# services:
#   server:
#     build: ./server
#     container_name: b_server
#     ports:
#       0
#   app:
#     build: .
#     restart: always
#     volumes:
#       - "/code/node_modules"
#       - ./:/code
#     ports:
#       - 4200:4200
#       - 3011:3011
#     command:
#       ng serve --host 0.0.0.0